version: '3'
services: 
  db: 
    image: postgres
    restart: always
    volumes: 
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
  vk:
    build: ./VkBot
    restart: always
  server:
    build: ./server
    restart: always
    depends_on: 
      - db
    ports:
      - "3000:3000"